dist:
    name: otel-cujprocessor
    description: Basic OpenTelemetry collector distribution for Developers
    output_path: ./dist
    otelcol_version: 0.108.1


exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.109.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.109.0


processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.109.0
  - gomod: github.com/trossignol/otelcustomprocessor v0.0.1


receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.109.0


replaces:
  - github.com/trossignol/otelcustomprocessor => ../src
